apiVersion: v1
kind: Service
metadata:
  name: next-self-hosted
  namespace: default
spec:
  selector:
    app: next-self-hosted
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
